name: Terraform Workflow for CI

on:
  push:
    branches:
      - main
      - featureahishbranch

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write


jobs:
  Terraform-Build-Automation-CI:

    runs-on: ubuntu-latest

    steps:

      - name: Terraform Checkout and Clone the Repository
        uses: actions/checkout@v4


      - name: Terraform Security Scan tool (tfsec)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: true


      - name: Terraform Hashicorp Setup Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Azure Login
        uses: Azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      - name: Terraform Init Infra Code Deployment
        id: init
        working-directory: ./Environments/Dev
        run: terraform init


      - name: Terraform Format Check
        working-directory: ./Environments/Dev
        run: terraform fmt -check


      - name: Terraform Validate
        working-directory: ./Environments/Dev
        run: terraform validate


      - name: Terraform Plan
        id: plan
        working-directory: ./Environments/Dev
        run: terraform plan


